# https://docs.codecov.io/docs/codecov-yaml
# https://github.com/codecov/support/wiki/Codecov-Yaml

coverage:
  status:
    project:
      default: false
    patch:
      default: false

comment:
  layout: "diff"

flags:
  production:
    paths:
      - TunnelVisionLabs.ReferenceAssemblyAnnotator/
  test:
    paths:
      - TunnelVisionLabs.ReferenceAssemblyAnnotator.Test/
  # Filter results to only show debug reports until the accuracy problems with
  # the report merge process are fixed.
  Release:
    paths:
      - nonexistent/
